export const ProfileEvent = {
  getData: 'profile.model.clickGetData',
  clickChangeData: 'profile.model.clickChangeData',
  clickChangeAvatar: 'profile.model.clickChangeAvatar',
  profileAvatarWait: 'profile.view.profileAvatarWait',
  profileAvatarError: 'profile.view.profileAvatarError',
  profileAvatarSuccess: 'profile.view.profileAvatarSuccess',
  profileFormWait: 'profile.view.profileFormWait',
  profileFormError: 'profile.view.profileFormError',
  profileFormSuccess: 'profile.view.profileFormSuccess',
  login: 'login.controller.start',
  renderData: 'profile.view.renderData',
  exit: 'profile.model.exit',
  uploadAvatar: 'profile.model.exit',
  changeAvatarToBuffer: 'profile.view.changeAvatarToBuffer',
  originalAvatarFromBuffer: 'profile.view.originalAvatarFromBuffer',
  clearAvatarBuffer: 'profile.view.clearAvatarBuffer',
};

export const ProfileMessage = {
  waitAvatarСonfirmation: 'Нажмите кнопку «Изменить данные» что-бы применить изменение',
  waitData: 'Ожидаем ответ от сервера',
  success: 'Данные изменены',
  unknownError: 'Неизвестная ошибка',
  errorValidation: 'Некорректные данные',
  errorSize: 'Размер файла больше 15 MB',
  errorFormatImg: 'Неверный формат изображения',
  forbidden: 'Недостаточно прав',
  userUndefind: 'Пользователь не найден',
  emailNonUniq: 'Пользователь с такой почтой уже есть',
  emailErrorValidation: 'Почта не корректна',
  usernameErrorValidation: 'Логин не корректный',
  passwordErrorValidation: 'Пароль не корректный',
  repeatPasswordErrorValidation: 'Пароли не совпали',
};
